books-service:
 image: 10.62.39.153:5000/books-service
 privileged: true
 volumes:
  - books-service-data:/data/db
books-serviceLB:
 ports:
  - 9001:8080
 tty: true
 image: rancher/load-balancer-service
 links:
  - books-service:books-service
 stdin_open: true
